server:
  port: 80
  servlet:
    context-path: /Shophyol
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Aa123456
    url: jdbc:mysql://localhost:3306/shophyoldb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 147093724933-b7iqgrl6396scieiks26jo4jboh1e6um.apps.googleusercontent.com
            clientSecret: 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
            scope:
            - email
            - profile
            

  main:
    allow-circular-references: true          
